"""empty message

Revision ID: 9f7e6c2849ba
Revises: 43b60d497630
Create Date: 2020-09-07 22:09:52.953724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7e6c2849ba'
down_revision = '43b60d497630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spy_id', sa.String(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('session', sa.Column('spy_current_song', sa.String(), nullable=True))
    op.add_column('user_token', sa.Column('socket_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_token', 'socket_id')
    op.drop_column('session', 'spy_current_song')
    op.drop_table('song')
    # ### end Alembic commands ###
